### ISSUE TITLE
Investigate "ba_prop_club_emis_rig_01" and "cs6_08_props_combo0120_90_lod" collision

### ISSUE THREAD

**Issue by Sainan** [Sainan/gta-v-joaat-hash-db#1]

**Comment by Sainan** [comment]
@DurtyFree sorry for the ping, but I believe this is an issue with your data

**Comment by DurtyFree** [comment]
hi, can you describe further?

**Comment by Sainan** [comment]
I believe "cs6_08_props_combo0120_90_lod" is made-up because it collides with "ba_prop_club_emis_rig_01" which seems to be the real key, but your data has it wrong: https://forge.plebmasters.de/objects/cs6_08_props_combo0120_90_lod

**Comment by DurtyFree** [comment]
Ah i see, I just digged into it and it seems to be a collision in codewalker. The model name is picked up from a related ytyp `update\x64\dlcpacks\mpbattle\dlc1.rpf\x64\levels\gta5\props\prop_battle_lights_02.rpf\ba_prop_battle_lights_02.ytyp` which lists the name `cs6_08_props_combo0120_90_lod` as associated asset name, which doesnt exist as a model but is a collision to the real one (ba_prop_club_emis_rig_01), so thats where this name came from.

Not sure if I will dig into this further, seems to be a rare case of a collision

**Comment by Sainan** [comment]
Ah, so you also got the name from elsewhere? I'm just kinda concerned that someone has been making up hash names and now my database might be poisoned, but oh well. Thanks for looking into it, and I hope you can at least correct this in your data.

**Comment by DurtyFree** [comment]
I fixed this collision manually, sadly I cannot know whether something is a collision or not :/ I will try something out but feel free to let me know if you find any more issues / collisions.
You can also drop me a message at discord: DurtyFree#3216

https://forge.plebmasters.de/objects/ba_prop_club_emis_rig_01

**Comment by DurtyFree** [comment]
I have found more invalid hash collisions and fixed it:
```
            { "cs6_08_props_combo0120_90_lod", "ba_prop_club_emis_rig_01" },
            { "0", "p_mp_door_07" },
            { "s_m_m_pilot_85_lod", "v_39_ventilation" },
            { "hw1_02_247_10_lod", "kt1_16_dirt0302" },
            { "id1_26b_26_lod", "vb_rd_cablemesh9665_thvy001" },
            { "a_f_y_soucent_17_lod", "ch2_05d_upper_res4_dtl" },
            { "sc1_props_combo0804_77_lod", "cs1_13_houses" },
            { "ch2_02_retwall00_lod_lod", "cs1_11_decals17" },
            { "ch1_05_props_combo53_92_lod", "cs3_07_glue_05" },
            { "ch1_10_props_combo34_62_lod", "cs3_07_props_wire_025" },
            { "cs1_07_props_combo23_97_lod", "ar_prop_gate_cp_90d_01b_l2" },
            { "dlc_gtao_heist_planning_board_heist_board_print", "bkr_prop_prtmachine_dryer" },
            { "ch2_03_land06_lodb", "ex_office_01c_floorlamp_recept" }
     ```
