### ISSUE TITLE
Add credits in README

### ISSUE THREAD

**Issue by DurtyFree** [Sainan/gta-v-joaat-hash-db#2]
Hi,

please add credits & link your data sources, AFAIK you got some of the data from me like:
my data dumps github repo: https://github.com/DurtyFree/gta-v-data-dumps
my gta data website: https://forge.plebmasters.de/
my released 5mods object list: https://www.gta5-mods.com/misc/complete-object-list-for-menyoo-menu-cayo-perico-heist-update

thx

**Comment by Sainan** [comment]
This is such a huge scrape-data project, it would be impossible for me to find ever single "contributor". Just be happy I let you know when I found an issue with (what I thought was) your data. 🙃
