### ISSUE TITLE
How to use it to decrypt tunables file ?

### ISSUE THREAD

**Issue by Apokalypt** [Sainan/gta-v-joaat-hash-db#8]
Hello,
I would like to create a totally free tool that decrypts and generates a report when the tunables file changes. This report would allow to quickly consult all the changes.
I have already figured out how to decrypt the file to get the data in JSON format but I can't figure out how to get from the keys to the readable value.. I looked at the associations you had on your Github ( example: 0x01B3B476, tuner_bin_price_calico ) but it doesn't seem to match what I see in the file (when the calico was in reduction, the key in the decrypted file was: "D129CE9" )

Would you be able to help me understand how it works so I can implement this tool please?

**Comment by Sainan** [comment]
Your tool sounds interesting but I'm afraid open-source software does not mean I do the work for you. This repository works to map the hashes in the game scripts to names. How those hashes come to be used and how they relate to some JSON file is out-of-scope, I'm afraid.
